import { Venue, Event, Offer } from './types';

export const venues: Venue[] = [
  // ============================================
  // RESTAURANTS (8)
  // ============================================
  {
    id: 'griffin-tavern',
    slug: 'griffin-tavern',
    name: 'Griffin Tavern Kitchen and Taphouse',
    type: 'restaurant',
    description: "Spokane's newest neighborhood hot spot, located across from the Martin Woldson Theater at the Fox in the heart of downtown's entertainment district. This modern tavern pairs timeless British pub fare with local favorites, features Eastern Washington's first self-pour beer wall, and offers a unique private dining space hidden behind a secret door.",
    shortDescription: 'Modern tavern with self-pour beer wall and British pub fare',
    address: '301 W Riverside Ave, Spokane, WA 99201',
    phone: '(509) 747-3464',
    heroImage: '/images/venues/griffin-tavern-interior.webp',
    thumbnail: '/images/venues/griffin-tavern-exterior.webp',
    gallery: [
      '/images/venues/griffin-tavern-interior.webp',
      '/images/venues/griffin-tavern-alternate.webp',
      '/images/venues/griffin-tavern-food.webp',
    ],
    cuisineType: ['British', 'American', 'Pub Food'],
    priceRange: 2,
    features: ['Self-Pour Beer Wall', 'Private Dining', 'Happy Hour', 'Outdoor Seating'],
    hours: {
      'Monday-Thursday': '11:00 AM - 10:00 PM',
      'Friday-Saturday': '11:00 AM - 11:00 PM',
      'Sunday': '10:00 AM - 9:00 PM',
    },
    coordinates: { lat: 47.6588, lng: -117.4260 },
    isActive: true,
    isFeatured: true,
  },
  {
    id: 'steam-plant',
    slug: 'steam-plant',
    name: 'Steam Plant Restaurant & Brew Pub',
    type: 'restaurant',
    description: 'One of the few historically renovated steam plants in the nation. The restaurant uses a wood burning oven for fresh pizzas and creates mouth-watering American food with flavorful and thoughtfully selected ingredients.',
    shortDescription: 'Historic steam plant with wood-fired pizzas',
    address: '159 S Lincoln St, Spokane, WA 99201',
    phone: '(509) 777-3900',
    heroImage: '/images/venues/steam-plant-bar.webp',
    thumbnail: '/images/venues/steam-plant-exterior.webp',
    gallery: [
      '/images/venues/steam-plant-interior.webp',
      '/images/venues/steam-plant-dining.webp',
      '/images/venues/steam-plant-bar-dining.webp',
      '/images/venues/steam-plant-banquet-room.webp',
    ],
    cuisineType: ['American', 'Pizza', 'Brewery'],
    priceRange: 2,
    features: ['Wood-Fired Pizza', 'Craft Beer', 'Historic Building', 'Patio'],
    hours: {
      'Monday-Thursday': '11:00 AM - 10:00 PM',
      'Friday-Saturday': '11:00 AM - 11:00 PM',
      'Sunday': '10:00 AM - 9:00 PM',
    },
    coordinates: { lat: 47.6577, lng: -117.4252 },
    isActive: true,
    isFeatured: true,
  },
  {
    id: 'osprey-restaurant',
    slug: 'osprey-restaurant',
    name: 'Osprey Restaurant & Bar',
    type: 'restaurant',
    description: 'Riverside dining at Ruby River Hotel featuring live music, craft cocktails, and fresh Pacific Northwest cuisine with stunning views of the Spokane River.',
    shortDescription: 'Riverside dining with live music and river views',
    address: '700 N Division St, Spokane, WA 99202',
    phone: '(509) 326-5577',
    heroImage: '/images/venues/osprey-interior.webp',
    thumbnail: '/images/venues/osprey-patio.webp',
    gallery: [
      '/images/venues/osprey-interior.webp',
      '/images/venues/osprey-dining.webp',
      '/images/venues/osprey-patio.webp',
      '/images/venues/osprey-food.webp',
    ],
    cuisineType: ['American', 'Pacific Northwest', 'Cocktails'],
    priceRange: 3,
    features: ['Live Music', 'River Views', 'Craft Cocktails', 'Sunday Brunch'],
    hours: {
      'Monday-Thursday': '4:00 PM - 10:00 PM',
      'Friday-Saturday': '4:00 PM - 11:00 PM',
      'Sunday': '10:00 AM - 9:00 PM',
    },
    coordinates: { lat: 47.6701, lng: -117.4251 },
    isActive: true,
    isFeatured: true,
  },
  {
    id: 'sapphire-lounge',
    slug: 'sapphire-lounge',
    name: 'Sapphire Lounge',
    type: 'restaurant',
    description: "In Spokane's vibrant downtown Entertainment District, Sapphire Lounge is the go-to spot for locals and travelers. Our skilled bartenders craft exceptional cocktails while providing top-notch service.",
    shortDescription: 'Craft cocktail lounge in the entertainment district',
    address: '901 W 1st Ave, Spokane, WA 99201',
    phone: '(509) 747-1041',
    heroImage: '/images/venues/sapphire-lounge-interior.webp',
    thumbnail: '/images/venues/sapphire-lounge-exterior.webp',
    gallery: [
      '/images/venues/sapphire-lounge-interior.webp',
      '/images/venues/sapphire-lounge-food.webp',
    ],
    cuisineType: ['Cocktails', 'Small Plates'],
    priceRange: 2,
    features: ['Craft Cocktails', 'Late Night', 'Happy Hour', 'Live Music'],
    hours: {
      'Monday-Thursday': '3:00 PM - 12:00 AM',
      'Friday-Saturday': '3:00 PM - 2:00 AM',
      'Sunday': 'Closed',
    },
    coordinates: { lat: 47.6587, lng: -117.4280 },
    isActive: true,
    isFeatured: false,
  },
  {
    id: 'rosies',
    slug: 'rosies',
    name: "Rosie's Restaurant",
    type: 'restaurant',
    description: 'Step into the nostalgic charm of Rosie\'s, where the cozy ambiance transports you back to a simpler time. Classic diner favorites like bacon and eggs, fluffy pancakes, or hearty biscuits and gravy. Complimentary breakfast for Hotel Ruby guests.',
    shortDescription: 'Classic American diner with nostalgic charm',
    address: '901 W 1st Ave, Spokane, WA 99201',
    phone: '(509) 747-1041',
    heroImage: '/images/venues/rosies-interior.webp',
    thumbnail: '/images/venues/rosies-exterior.webp',
    gallery: [
      '/images/venues/rosies-food-1.webp',
      '/images/venues/rosies-food.webp',
      '/images/venues/rosies-dining-image.jpg.webp',
    ],
    cuisineType: ['American', 'Breakfast', 'Diner'],
    priceRange: 1,
    features: ['All-Day Breakfast', 'Complimentary for Hotel Guests', 'Classic Diner'],
    hours: {
      'Daily': '6:00 AM - 2:00 PM',
    },
    coordinates: { lat: 47.6587, lng: -117.4280 },
    isActive: true,
    isFeatured: false,
  },
  {
    id: 'gilded-unicorn',
    slug: 'gilded-unicorn',
    name: 'The Gilded Unicorn',
    type: 'restaurant',
    description: 'An enchanted haven where Modern American Classics come to life through handcrafted wonders and magical libations. Nestled beneath the Historic Montvale Hotel with an old-world feel that whispers tales of Spokane\'s rich history.',
    shortDescription: 'Enchanted restaurant with modern American classics',
    address: '1005 W 1st Ave, Spokane, WA 99201',
    phone: '(509) 747-1919',
    heroImage: '/images/venues/gilded-unicorn-interior.webp',
    thumbnail: '/images/venues/gilded-unicorn-exterior.webp',
    gallery: [
      '/images/venues/gilded-unicorn-bar.webp',
      '/images/venues/gilded-unicorn-food.webp',
      '/images/venues/gilded-unicorn-interior.webp',
    ],
    cuisineType: ['American', 'Fine Dining', 'Cocktails'],
    priceRange: 3,
    features: ['Historic Setting', 'Craft Cocktails', 'Date Night', 'Underground Location'],
    hours: {
      'Tuesday-Saturday': '5:00 PM - 10:00 PM',
      'Sunday-Monday': 'Closed',
    },
    coordinates: { lat: 47.6586, lng: -117.4290 },
    isActive: true,
    isFeatured: true,
  },
  {
    id: 'carusos',
    slug: 'carusos',
    name: "Caruso's Sandwiches & Artisan Pizza",
    type: 'restaurant',
    description: 'Fresh artisan sandwiches and wood-fired pizza in Spokane\'s University District. Casual, friendly atmosphere with quality ingredients and generous portions.',
    shortDescription: 'Artisan sandwiches and wood-fired pizza',
    address: '920 N Ruby St, Spokane, WA 99202',
    phone: '(509) 326-7214',
    heroImage: '/images/venues/carusos-interior.webp',
    thumbnail: '/images/venues/carusos-sandwiches.jpg',
    gallery: [
      '/images/venues/carusos-interior.webp',
      '/images/venues/carusos-pizza.webp',
      '/images/venues/carusos-sandwiches.webp',
    ],
    cuisineType: ['Italian', 'Pizza', 'Sandwiches'],
    priceRange: 2,
    features: ['Wood-Fired Pizza', 'Artisan Sandwiches', 'Casual Dining', 'Takeout'],
    hours: {
      'Monday-Friday': '11:00 AM - 8:00 PM',
      'Saturday': '12:00 PM - 8:00 PM',
      'Sunday': 'Closed',
    },
    coordinates: { lat: 47.6720, lng: -117.4010 },
    isActive: true,
    isFeatured: false,
  },
  {
    id: 'farmhouse-kitchen',
    slug: 'farmhouse-kitchen',
    name: 'Farmhouse Kitchen + Bar',
    type: 'restaurant',
    description: 'Farm-to-table dining featuring locally sourced ingredients and seasonal menus. Rustic-chic atmosphere with creative cocktails and craft beers.',
    shortDescription: 'Farm-to-table dining with seasonal menus',
    address: '3707 S Grand Blvd, Spokane, WA 99203',
    phone: '(509) 443-3000',
    heroImage: '/images/venues/farmhouse-interior.webp',
    thumbnail: '/images/venues/farmhouse-exterior.webp',
    gallery: [
      '/images/venues/farmhouse-interior.webp',
      '/images/venues/farmhouse-food.webp',
      '/images/venues/farmhouse-bar.webp',
    ],
    cuisineType: ['American', 'Farm-to-Table', 'Seasonal'],
    priceRange: 2,
    features: ['Farm-to-Table', 'Seasonal Menu', 'Craft Cocktails', 'Outdoor Seating'],
    hours: {
      'Monday-Thursday': '11:00 AM - 9:00 PM',
      'Friday-Saturday': '11:00 AM - 10:00 PM',
      'Sunday': '10:00 AM - 9:00 PM',
    },
    coordinates: { lat: 47.6320, lng: -117.4050 },
    isActive: true,
    isFeatured: false,
  },

  // ============================================
  // HOTELS (7)
  // ============================================
  {
    id: 'ruby-river-hotel',
    slug: 'ruby-river-hotel',
    name: 'Ruby River Hotel',
    type: 'hotel',
    description: 'Discover the hidden gem of Spokane at Ruby River Hotel, where breathtaking views of the Spokane River meet the charm of eight acres of lush grounds. With 241 beautifully designed rooms and suites, outdoor pools, playground, and prime access to Spokane\'s top attractions. Dog-friendly, family-inspired atmosphere with riverside location.',
    shortDescription: 'Riverfront resort hotel with pools and family amenities',
    address: '700 N Division St, Spokane, WA 99202',
    phone: '(509) 326-5577',
    heroImage: '/images/venues/ruby-river-exterior.webp',
    thumbnail: '/images/venues/ruby-river-pool.webp',
    gallery: [
      '/images/venues/ruby-river-exterior.webp',
      '/images/venues/ruby-river-pool.webp',
      '/images/venues/ruby-river-room.webp',
    ],
    cuisineType: [],
    features: ['Outdoor Pools', 'Playground', 'Dog Friendly', 'River Views', 'Event Space', 'Osprey Restaurant'],
    hours: {
      'Check-in': '3:00 PM',
      'Check-out': '11:00 AM',
    },
    coordinates: { lat: 47.6701, lng: -117.4251 },
    isActive: true,
    isFeatured: true,
  },
  {
    id: 'hotel-ruby-spokane',
    slug: 'hotel-ruby-spokane',
    name: 'Hotel Ruby | Spokane',
    type: 'hotel',
    description: 'Discover the glow of Spokane\'s nightlife when you stay at Hotel Ruby, just steps from the city\'s best concert houses, theaters, and dining. Boutique hotel in the heart of downtown\'s Entertainment District with fun vibes and great value. Features Sapphire Lounge and complimentary breakfast at Rosie\'s Restaurant.',
    shortDescription: 'Boutique hotel in downtown entertainment district',
    address: '901 W 1st Ave, Spokane, WA 99201',
    phone: '(509) 747-1041',
    heroImage: '/images/venues/hotel-ruby-spokane.jpeg',
    thumbnail: '/images/venues/hotel-ruby-spokane.jpeg',
    gallery: [
      '/images/venues/hotel-ruby-exterior.webp',
      '/images/venues/hotel-ruby-room.webp',
      '/images/venues/hotel-ruby-lounge.webp',
    ],
    cuisineType: [],
    features: ['Downtown Location', 'Dog Friendly', 'Sapphire Lounge', 'Free Breakfast', 'Complimentary Bikes', 'Parking Available'],
    hours: {
      'Check-in': '3:00 PM',
      'Check-out': '11:00 AM',
    },
    coordinates: { lat: 47.6587, lng: -117.4280 },
    isActive: true,
    isFeatured: true,
  },
  {
    id: 'montvale-hotel',
    slug: 'montvale-hotel',
    name: 'Montvale Hotel',
    type: 'hotel',
    description: 'Historic boutique hotel in downtown Spokane, beautifully restored with old-world charm and modern amenities. Home to the enchanted Gilded Unicorn restaurant. Perfect for those seeking a unique, intimate hotel experience with character and history.',
    shortDescription: 'Historic boutique hotel with old-world charm',
    address: '1005 W 1st Ave, Spokane, WA 99201',
    phone: '(509) 747-1919',
    heroImage: '/images/venues/montvale-exterior.webp',
    thumbnail: '/images/venues/montvale-room.webp',
    gallery: [
      '/images/venues/montvale-exterior.webp',
      '/images/venues/montvale-room.webp',
      '/images/venues/montvale-lobby.webp',
    ],
    cuisineType: [],
    features: ['Historic Building', 'Gilded Unicorn Restaurant', 'Downtown Location', 'Boutique Experience', 'Event Space'],
    hours: {
      'Check-in': '3:00 PM',
      'Check-out': '11:00 AM',
    },
    coordinates: { lat: 47.6586, lng: -117.4290 },
    isActive: true,
    isFeatured: true,
  },
  {
    id: 'steam-plant-hotel',
    slug: 'steam-plant-hotel',
    name: 'Steam Plant Hotel',
    type: 'hotel',
    description: 'Boutique hotel within the historic Steam Plant building, offering unique accommodations with industrial-chic design. Adjacent to Steam Plant Restaurant and event spaces.',
    shortDescription: 'Boutique hotel in historic steam plant building',
    address: '159 S Lincoln St, Spokane, WA 99201',
    phone: '(509) 777-3900',
    heroImage: '/images/venues/steam-plant-hotel-spokane.jpg',
    thumbnail: '/images/venues/steam-plant-hotel-spokane.jpg',
    gallery: [
      '/images/venues/steam-plant-hotel-room.webp',
      '/images/venues/steam-plant-hotel-lobby.webp',
      '/images/venues/steam-plant-hotel-exterior.webp',
    ],
    cuisineType: [],
    features: ['Historic Building', 'Industrial Design', 'Steam Plant Restaurant', 'Event Space', 'Downtown Location'],
    hours: {
      'Check-in': '3:00 PM',
      'Check-out': '11:00 AM',
    },
    coordinates: { lat: 47.6577, lng: -117.4252 },
    isActive: true,
    isFeatured: false,
  },
  {
    id: 'madison-inn',
    slug: 'madison-inn',
    name: 'Madison Inn',
    type: 'hotel',
    description: 'Comfortable and affordable accommodations in Spokane. Perfect for extended stays and business travelers seeking value and convenience.',
    shortDescription: 'Comfortable accommodations with great value',
    address: '1810 N Madison St, Spokane, WA 99205',
    phone: '(509) 325-4600',
    heroImage: '/images/venues/madison-inn-spokane.jpg.webp',
    thumbnail: '/images/venues/madison-inn-spokane.jpg.webp',
    gallery: [
      '/images/venues/madison-inn-exterior.webp',
      '/images/venues/madison-inn-room.webp',
      '/images/venues/madison-inn-lobby.webp',
    ],
    cuisineType: [],
    features: ['Affordable Rates', 'Extended Stay', 'Business Friendly', 'Free Parking', 'Pet Friendly'],
    hours: {
      'Check-in': '3:00 PM',
      'Check-out': '11:00 AM',
    },
    coordinates: { lat: 47.6780, lng: -117.4180 },
    isActive: true,
    isFeatured: false,
  },
  {
    id: 'ruby-suites',
    slug: 'ruby-suites',
    name: 'Ruby Suites',
    type: 'hotel',
    description: 'Extended stay suites combining the warmth of home with exceptional hotel services. Perfect for stays of 30 days or more, featuring fully equipped kitchens and spacious living areas.',
    shortDescription: 'Extended stay suites for longer visits',
    address: '211 S Division St, Spokane, WA 99202',
    phone: '(509) 455-9600',
    heroImage: '/images/venues/ruby-suites-spokane.jpg',
    thumbnail: '/images/venues/ruby-suites-spokane.jpg',
    gallery: [
      '/images/venues/ruby-suites-suite.webp',
      '/images/venues/ruby-suites-kitchen.webp',
      '/images/venues/ruby-suites-exterior.webp',
    ],
    cuisineType: [],
    features: ['Extended Stay', 'Full Kitchen', 'Spacious Suites', 'Weekly/Monthly Rates', 'Pet Friendly'],
    hours: {
      'Check-in': '3:00 PM',
      'Check-out': '11:00 AM',
    },
    coordinates: { lat: 47.6620, lng: -117.4260 },
    isActive: true,
    isFeatured: false,
  },
  {
    id: 'hotel-ruby-sandpoint',
    slug: 'hotel-ruby-sandpoint',
    name: 'Hotel Ruby Sandpoint | Ponderay',
    type: 'hotel',
    description: 'Sister property in beautiful Sandpoint, Idaho. Offering the same Ruby Hospitality experience with mountain views and proximity to Lake Pend Oreille and Schweitzer Mountain Resort.',
    shortDescription: 'Ruby hospitality in scenic Sandpoint, Idaho',
    address: '477024 Highway 95, Ponderay, ID 83852',
    phone: '(208) 263-3194',
    heroImage: '/images/venues/hotel-ruby-sandpoint.jpg.webp',
    thumbnail: '/images/venues/hotel-ruby-sandpoint.jpg.webp',
    gallery: [
      '/images/venues/ruby-sandpoint-exterior.webp',
      '/images/venues/ruby-sandpoint-room.webp',
      '/images/venues/ruby-sandpoint-pool.webp',
    ],
    cuisineType: [],
    features: ['Mountain Views', 'Lake Access', 'Ski Resort Nearby', 'Pool', 'Pet Friendly'],
    hours: {
      'Check-in': '3:00 PM',
      'Check-out': '11:00 AM',
    },
    coordinates: { lat: 48.3050, lng: -116.5340 },
    isActive: true,
    isFeatured: false,
  },

  // ============================================
  // VENUES (4)
  // ============================================
  {
    id: 'bing-theater',
    slug: 'bing-theater',
    name: 'Bing Theater',
    type: 'event_space',
    description: 'Historic theater in downtown Spokane featuring concerts, comedy shows, and special events. Named after the legendary Spokane native Bing Crosby. Seating capacity of 700 with full bar and concessions.',
    shortDescription: 'Historic downtown theater for live entertainment',
    address: '901 W Sprague Ave, Spokane, WA 99201',
    phone: '(509) 227-7638',
    heroImage: '/images/venues/bing-exterior.webp',
    thumbnail: '/images/venues/bing-exterior.webp',
    gallery: [
      '/images/venues/bing-interior.gif',
      '/images/venues/bing-exterior.webp',
    ],
    cuisineType: [],
    features: ['Historic Theater', 'Live Music', 'Comedy Shows', 'Full Bar', '700 Capacity'],
    hours: {
      'Varies by Show': 'Check event schedule',
    },
    coordinates: { lat: 47.6577, lng: -117.4280 },
    isActive: true,
    isFeatured: true,
  },
  {
    id: 'montvale-event-center',
    slug: 'montvale-event-center',
    name: 'Montvale Event Center',
    type: 'event_space',
    description: 'Elegant event space within the historic Montvale Hotel. Perfect for weddings, corporate events, and private celebrations with customizable spaces and full-service catering.',
    shortDescription: 'Elegant event space in historic hotel',
    address: '1005 W 1st Ave, Spokane, WA 99201',
    phone: '(509) 747-1919',
    heroImage: '/images/venues/montvale-event-center.jpg',
    thumbnail: '/images/venues/montvale-event-center.jpg',
    gallery: [
      '/images/venues/montvale-event-ballroom.webp',
      '/images/venues/montvale-event-setup.webp',
      '/images/venues/montvale-event-reception.webp',
    ],
    cuisineType: [],
    features: ['Weddings', 'Corporate Events', 'Full Catering', 'Historic Venue', 'Customizable Spaces'],
    hours: {
      'By Appointment': 'Contact for availability',
    },
    coordinates: { lat: 47.6586, lng: -117.4290 },
    isActive: true,
    isFeatured: true,
  },
  {
    id: 'steam-plant-events',
    slug: 'steam-plant-events',
    name: 'Steam Plant Restaurant + Events',
    type: 'event_space',
    description: 'Stunning event space within the historic Steam Plant. Features soaring ceilings, industrial architecture, and versatile spaces for events from 20 to 500 guests. Full catering available.',
    shortDescription: 'Historic industrial event space',
    address: '159 S Lincoln St, Spokane, WA 99201',
    phone: '(509) 777-3900',
    heroImage: '/images/venues/steam-plant-event-space.webp',
    thumbnail: '/images/venues/steam-plant-banquet-room.webp',
    gallery: [
      '/images/venues/steam-plant-event-space.webp',
      '/images/venues/steam-plant-banquet-room.webp',
      '/images/venues/steam-plant-event-setup.webp',
    ],
    cuisineType: [],
    features: ['Historic Building', 'Large Capacity', 'Full Catering', 'Industrial Charm', 'Flexible Spaces'],
    hours: {
      'By Appointment': 'Contact for availability',
    },
    coordinates: { lat: 47.6577, lng: -117.4252 },
    isActive: true,
    isFeatured: true,
  },
  {
    id: 'ruby-river-events',
    slug: 'ruby-river-events',
    name: 'Ruby River Events + Catering',
    type: 'event_space',
    description: 'Riverside event spaces with stunning Spokane River views. Perfect for weddings, corporate events, and celebrations. Features both indoor and outdoor spaces across 8 acres of grounds with professional catering from Osprey Restaurant.',
    shortDescription: 'Riverside events with spectacular views',
    address: '700 N Division St, Spokane, WA 99202',
    phone: '(509) 326-5577',
    heroImage: '/images/venues/ruby-river-wedding.webp',
    thumbnail: '/images/venues/ruby-river-inn-events.jpg.webp',
    gallery: [
      '/images/venues/ruby-river-wedding.webp',
      '/images/venues/ruby-river-event-space.webp',
      '/images/venues/ruby-river-outdoor-ceremony.webp',
    ],
    cuisineType: [],
    features: ['River Views', 'Outdoor Ceremonies', 'Indoor Reception', 'Full Catering', 'Wedding Packages'],
    hours: {
      'By Appointment': 'Contact for availability',
    },
    coordinates: { lat: 47.6701, lng: -117.4251 },
    isActive: true,
    isFeatured: true,
  },
];

export const events: Event[] = [
  {
    id: 'event-1',
    venueId: 'osprey-restaurant',
    venueName: 'Osprey Restaurant & Bar',
    title: 'Live Jazz Night',
    slug: 'live-jazz-night',
    description: 'Enjoy an evening of smooth jazz by the river. The Jazz Trio performs classic standards and contemporary favorites.',
    eventType: 'concert',
    posterUrl: 'https://images.unsplash.com/photo-1511735111819-9a3f7709049c?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1511735111819-9a3f7709049c?w=1200&q=80',
    startDateTime: '2024-11-15T20:00:00',
    doorsOpen: '7:00 PM',
    showTime: '8:00 PM',
    ticketPrice: 0,
    artistName: 'Spokane Jazz Trio',
    artistBio: 'Local jazz ensemble bringing timeless standards to life.',
    status: 'upcoming',
    isFeatured: true,
  },
  {
    id: 'event-2',
    venueId: 'bing-theater',
    venueName: 'Bing Theater',
    title: 'Comedy Night Extravaganza',
    slug: 'comedy-night',
    description: 'A night of laughter with touring comedians from across the country. Two headliners and special guest appearances.',
    eventType: 'comedy',
    posterUrl: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=1200&q=80',
    startDateTime: '2024-11-20T19:30:00',
    doorsOpen: '7:00 PM',
    showTime: '7:30 PM',
    ticketPriceRange: { min: 25, max: 45 },
    status: 'upcoming',
    isFeatured: true,
    capacity: 700,
    ticketsSold: 520,
  },
  {
    id: 'event-3',
    venueId: 'steam-plant',
    venueName: 'Steam Plant Restaurant',
    title: 'Wine Pairing Dinner',
    slug: 'wine-pairing-dinner',
    description: 'Five-course meal expertly paired with wines from Washington State. Limited seating available.',
    eventType: 'tasting',
    posterUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=1200&q=80',
    startDateTime: '2024-11-22T18:00:00',
    ticketPrice: 85,
    status: 'upcoming',
    isFeatured: true,
    capacity: 40,
    ticketsSold: 35,
  },
  {
    id: 'event-4',
    venueId: 'bing-theater',
    venueName: 'Bing Theater',
    title: 'Indie Rock Concert',
    slug: 'indie-rock-concert',
    description: 'Pacific Northwest indie band brings their latest album to Spokane. Opening act at 8 PM.',
    eventType: 'concert',
    posterUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200&q=80',
    startDateTime: '2024-11-25T20:00:00',
    doorsOpen: '7:30 PM',
    showTime: '8:00 PM',
    ticketPriceRange: { min: 30, max: 50 },
    artistName: 'The Northern Lights',
    artistBio: 'Seattle-based indie rock band known for their atmospheric sound and powerful live performances.',
    status: 'upcoming',
    isFeatured: false,
  },
  {
    id: 'event-5',
    venueId: 'osprey-restaurant',
    venueName: 'Osprey Restaurant & Bar',
    title: 'Acoustic Sunday',
    slug: 'acoustic-sunday',
    description: 'Relaxing Sunday afternoon with local acoustic performers. Enjoy brunch while listening to original songs.',
    eventType: 'concert',
    posterUrl: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800&q=80',
    heroImage: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=1200&q=80',
    startDateTime: '2024-11-17T13:00:00',
    ticketPrice: 0,
    status: 'upcoming',
    isFeatured: false,
  },
];

export const offers: Offer[] = [
  {
    id: 'offer-1',
    title: '🎉 Birthday Month Special',
    description: 'Complimentary dessert at any Ruby restaurant during your birthday month',
    offerType: 'freebie',
    validFrom: '2024-01-01T00:00:00',
    validUntil: '2024-12-31T23:59:59',
    backgroundImage: '/images/food/osprey-food.webp',
    backgroundColor: '#FFE4E1',
    textColor: '#8B0000',
    venues: ['griffin-tavern', 'steam-plant', 'osprey-restaurant', 'rosies', 'gilded-unicorn'],
    venueNames: ['Griffin Tavern', 'Steam Plant', 'Osprey', "Rosie's", 'Gilded Unicorn'],
    isFeatured: true,
    redemptionCode: 'BDAY2024',
    termsAndConditions: 'Valid with proof of birthday. One per customer per year. Not valid with other offers.',
  },
  {
    id: 'offer-2',
    title: '⚡ Happy Hour Flash Sale',
    description: '$2 off all self-pour beers at Griffin Tavern',
    offerType: 'flash',
    validFrom: '2024-11-08T15:00:00',
    validUntil: '2024-11-08T18:00:00',
    backgroundColor: '#FFF8DC',
    textColor: '#8B0000',
    venues: ['griffin-tavern'],
    venueNames: ['Griffin Tavern'],
    isFeatured: true,
    redemptionCode: 'HAPPYHOUR',
  },
  {
    id: 'offer-3',
    title: '🎵 Early Access: Concert Tickets',
    description: 'Get presale tickets to upcoming shows at the Bing before general public',
    offerType: 'early_access',
    validFrom: '2024-11-01T00:00:00',
    validUntil: '2024-11-30T23:59:59',
    backgroundColor: '#E6F3FF',
    textColor: '#1C1C1E',
    venues: ['bing-theater'],
    venueNames: ['Bing Theater'],
    isFeatured: true,
  },
  {
    id: 'offer-4',
    title: 'Hotel Guest Exclusive',
    description: '20% off dinner at any restaurant when you show your room key',
    offerType: 'exclusive',
    validFrom: '2024-11-01T00:00:00',
    validUntil: '2024-12-31T23:59:59',
    backgroundColor: '#F0E6FF',
    textColor: '#4A0E4E',
    venues: ['griffin-tavern', 'steam-plant', 'osprey-restaurant', 'gilded-unicorn'],
    venueNames: ['Griffin Tavern', 'Steam Plant', 'Osprey', 'Gilded Unicorn'],
    isFeatured: false,
    redemptionCode: 'HOTELGUEST',
  },
  {
    id: 'offer-5',
    title: 'Weekend Brunch Special',
    description: 'Free mimosa with any brunch entree at Osprey Restaurant',
    offerType: 'freebie',
    validFrom: '2024-11-09T10:00:00',
    validUntil: '2024-11-10T15:00:00',
    backgroundImage: '/images/food/osprey-food.webp',
    backgroundColor: '#FFF4E6',
    textColor: '#8B0000',
    venues: ['osprey-restaurant'],
    venueNames: ['Osprey Restaurant & Bar'],
    isFeatured: true,
    redemptionCode: 'BRUNCH',
  },
];

// Helper function to get featured content
export function getFeaturedVenues(): Venue[] {
  return venues.filter(v => v.isFeatured);
}

export function getFeaturedEvents(): Event[] {
  return events.filter(e => e.isFeatured && e.status === 'upcoming');
}

export function getFeaturedOffers(): Offer[] {
  return offers.filter(o => o.isFeatured);
}

export function getVenueById(id: string): Venue | undefined {
  return venues.find(v => v.id === id || v.slug === id);
}

export function getEventById(id: string): Event | undefined {
  return events.find(e => e.id === id);
}

export function getOfferById(id: string): Offer | undefined {
  return offers.find(o => o.id === id);
}

export function getEventsByVenue(venueId: string): Event[] {
  return events.filter(e => e.venueId === venueId && e.status === 'upcoming');
}

export function getUpcomingEvents(): Event[] {
  return events
    .filter(e => e.status === 'upcoming')
    .sort((a, b) => new Date(a.startDateTime).getTime() - new Date(b.startDateTime).getTime());
}